##
## {{ORGANISATION}} PROJECT, {{year}}
## {{display_name}}
## File description:
## Makefile used to build
## the project
##

NAME = {{name}}

ifndef HC
	HC = ghc
endif

SRC_FILES =	\
			src/Main.hs							\

OBJ_FILES = $(SRC_FILES:.hs=.o)

.PHONY: all clean fclean re

all: $(NAME)

%.o: %.hs
	@$(HC) -c $< -o $@
	@echo 'hc -c $<'

$(NAME): $(OBJ_FILES)
	@$(HC) $(OBJ_FILES) -o $@
	@echo 'hc -o $@'
	@printf "\033[32m%s\033[0m\n" "successfully built $@"

clean:
	@rm -f $(OBJ_FILES)
	@rm -f $(OBJ_FILES:.o=.hi)

fclean: clean
	@rm -f $(NAME)

re: fclean all
